name: Mettre à jour les statistiques RPA

on:
  schedule:
    - cron: '0 7 * * 1'  
  workflow_dispatch:     

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v4

    - name: Installer cloc
      run: sudo apt-get install -y cloc

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Installer dépendances Python
      run: pip install requests

    - name: Exécuter le script de génération
      run: python scripts/generate_stats.py

    - name: Commit & push si changements
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add profile/README.md stats.html
        git commit -m "🔄 Mise à jour automatique des stats" || echo "Aucun changement"
        git push
